/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./pages/__root"
import { Route as IndexImport } from "./pages/index"
import { Route as IframeIndexImport } from "./pages/iframe/index"
import { Route as FeedIdIndexImport } from "./pages/feed/$id/index"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const IframeIndexRoute = IframeIndexImport.update({
  path: "/iframe/",
  getParentRoute: () => rootRoute,
} as any)

const FeedIdIndexRoute = FeedIdIndexImport.update({
  path: "/feed/$id/",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/iframe/": {
      id: "/iframe/"
      path: "/iframe"
      fullPath: "/iframe"
      preLoaderRoute: typeof IframeIndexImport
      parentRoute: typeof rootRoute
    }
    "/feed/$id/": {
      id: "/feed/$id/"
      path: "/feed/$id"
      fullPath: "/feed/$id"
      preLoaderRoute: typeof FeedIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  IframeIndexRoute,
  FeedIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/",
        "/iframe/",
        "/feed/$id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/iframe/": {
      "filePath": "iframe/index.tsx"
    },
    "/feed/$id/": {
      "filePath": "feed/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
